name-template: "Release ${{ nextReleaseVersion }} 🚀"
tag-template: "v${{ nextReleaseVersion }}"

categories:
  - title: "🌟 Features"
    labels:
      - "feature"
  - title: "🐛 Bug Fixes"
    labels:
      - "fix"
  - title: "📄 Documentation"
    labels:
      - "docs"
  - title: "🧰 Maintenance"
    labels:
      - "chore"
      - "refactor"

change-template: "- $TITLE by @$AUTHOR"
no-labels-template: "- $TITLE (commit: [`$SHORT_SHA`](https://github.com/${{ github.repository }}/commit/$FULL_SHA))"

template: |
  ## What's Changed
  $CHANGES

  ---
  **Full commit history:** [Compare Changes](https://github.com/${{ github.repository }}/compare/${{ previousTag | default: 'N/A' }}...${{ currentTag | default: 'N/A' }})
