name-template: "Release ${{ nextReleaseVersion }} 🚀"
tag-template: "v${{ nextReleaseVersion }}"

categories:
  - title: "🚀 Features"
    labels:
      - "feature"
  - title: "🐛 Bug Fixes"
    labels:
      - "bug"
  - title: "🛠️ Maintenance"
    labels:
      - "chore"
      - "refactor"

change-template: "- $TITLE by @$AUTHOR in #$NUMBER"

template: |
  ## What's Changed
  $CHANGES
