name-template: "Release ${{ nextReleaseVersion }} 🚀"
tag-template: "v${{ nextReleaseVersion }}"

categories:
  - title: "🚀 Features"
    labels:
      - "feature"
  - title: "🐛 Bug Fixes"
    labels:
      - "bug"
  - title: "🛠️ Maintenance"
    labels:
      - "chore"
      - "refactor"
  - title: "🧩 Dependencies"
    labels:
      - "dependencies"

change-template: "- $TITLE by @$AUTHOR in #$NUMBER"

# Capture direct commits (without PR)
no-labels-merge-method: "title"
no-labels-template: "- $TITLE (commit: [`$SHORT_SHA`](https://github.com/{{github.repository}}/commit/$FULL_SHA))"

# Ignore changes in .github
exclude-labels:
  - "ignore-changelog"
  - "skip-release"
exclude-contributors:
  - "github-actions[bot]"

template: |
  ## What's Changed
  $CHANGES

  ## 📦 Full Changelog
  repository: `{{github.repository}}`  
  previousTag: `{{previousTag}}`  
  currentTag: `{{currentTag}}`  
  [Compare Changes](https://github.com/{{github.repository}}/compare/{{previousTag}}...{{currentTag}})
