name-template: 'Release ${{ nextReleaseVersion }} 🚀'
tag-template: 'v${{ nextReleaseVersion }}'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
  - title: '🛠️ Maintenance'
    labels:
      - 'chore'
      - 'refactor'
  - title: '🧩 Dependencies'
    labels:
      - 'dependencies'
change-template: '- $TITLE by @$AUTHOR in #$NUMBER'
template: |
  ## What's Changed
  $CHANGES

  ## 📦 Full Changelog
  [Compare Changes](https://github.com/${{ github.repository }}/compare/${{ previousTag }}...${{ currentTag }})
