name-template: "Release ${{ nextReleaseVersion }} 🚀"
tag-template: "v${{ nextReleaseVersion }}"
version-template: "${{ nextReleaseVersion }}"

categories:
  - title: "🚀 Features"
    labels:
      - "feature"
  - title: "🐛 Bug Fixes"
    labels:
      - "bug"
  - title: "🛠️ Maintenance"
    labels:
      - "chore"
      - "refactor"
  - title: "🧩 Dependencies"
    labels:
      - "dependencies"

change-template: "- $TITLE by @$AUTHOR in #$NUMBER"

no-labels-merge-method: "title"
no-labels-template: "- $TITLE (commit: [`$SHORT_SHA`](https://github.com/${{ github.repository }}/commit/$FULL_SHA))"

template: |
  ## What's Changed
  $CHANGES

  ## 📦 Full Changelog
  repository: `${{ github.repository }}`  
  previousTag: `${{ github.event.workflow_run.outputs.previous_tag | default: 'N/A' }}`  
  currentTag: `${{ github.event.workflow_run.outputs.current_tag | default: 'N/A' }}`  
  [Compare Changes](https://github.com/${{ github.repository }}/compare/${{ github.event.workflow_run.outputs.previous_tag | default: 'N/A' }}...${{ github.event.workflow_run.outputs.current_tag | default: 'N/A' }})
