name-template: "Release ${{ nextReleaseVersion }} 🚀"
tag-template: "v${{ nextReleaseVersion }}"

categories:
  - title: "🚀 Features"
    labels:
      - "feature"
  - title: "🐛 Bug Fixes"
    labels:
      - "fix"
  - title: "🧩 Maintenance"
    labels:
      - "chore"
      - "refactor"
  - title: "🧩 Dependencies"
    labels:
      - "dependencies"

change-template: "- $TITLE by @$AUTHOR in #$NUMBER"
no-labels-template: "- $TITLE (commit: [`$SHORT_SHA`](https://github.com/${{ github.repository }}/commit/$FULL_SHA))"

template: |
  ## What's Changed
  $CHANGES
