name: .NET Windows Release 🚀

on:
  push:
    tags:
      - 'v*'  # Trigger for tags starting with 'v' (e.g., v1.0.0)
  workflow_dispatch:  # Allows manual execution from the GitHub Actions tab

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Build Project
      run: dotnet build --configuration Release

    - name: Publish Artifacts
      run: |
        mkdir release
        dotnet publish -c Release -o release

    - name: Create Zip Archive
      run: |
        zip -r release.zip release/

    - name: Draft Release
      id: draft_release
      uses: release-drafter/release-drafter@v5
      with:
        config-name: release-drafter.yml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish Release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ github.ref_name }}
        name: "Release ${{ github.ref_name }}"
        body: ${{ steps.draft_release.outputs.body }}
        artifacts: "release.zip"
        draft: false
        prerelease: false
