name: Update README 📝

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update README Links and Badges
        run: |
          bash .github/scripts/update-readme.sh

      - name: Commit Changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"
          git add README.md
          git diff --quiet && git diff --staged --quiet || git commit -m "Update README with repository info"
          git push
